### ISSUE TITLE
提个小优化

### ISSUE THREAD

**Issue by PerseveranceZ** [BryanAdamss/vue-awesome-template#8]
可以尝试使用动态 import 的方式，一些 index.js 做引入组装的文件就可以不用管了
https://github.com/PerseveranceZ/vue-develop-template/blob/master/src/service/api/index.js

**Comment by BryanAdamss** [comment]
已经优化过了（直接照抄😜）https://github.com/BryanAdamss/vue-awesome-template/commit/5b3a6c1a10e26c3b144643f680e315613d0838eb

- 没想到会被原作者翻牌🤣 顺带问两个问题吧
- 看了您的文章，在几个项目里也实践了，现在项目30w多行代码，自认为还是很清晰，可维护的。但我对plugins、services、utils层的理解还不是很深入，还望指点下。
  - 例如，我封装了一个[postmessage的库](https://github.com/BryanAdamss/vue-awesome-template/blob/master/src/plugins/messager.js)，我不知道应该放在哪层？
  - 它不包含业务逻辑，是一个独立库，我不确定是放在utils还是plugins里?
  类似的还有很多

- 我的理解是这样的
  - 项目相关的插件放到plugins里，如router、vuex、axios、routes-loader
  - 通用方法、类库放到utils，如时间转换
  - 包含业务属性的二次封装lib库全部放到services/extends里面，例如基于plugins/saver.js二次封装的[global-saver](https://github.com/BryanAdamss/vue-awesome-template/blob/master/src/services/extends/global-saver.js)

不知道理解可有偏差，还望指正!

**Comment by PerseveranceZ** [comment]
朋友客气了，大家都是互相学习，咱们理解的确实差不多。

如果你觉得比较重要，且项目当中经常调用的话，就放到 plugins 里面挂载到 vue 实例上，
如果只是个别页面用如果是我可能就会放到 utils 里面了。

services 里面就是放所有我需要的数据，只要是数据源我都会放进去。

其实放到哪里并不一定要按照我说的来，最重要的是你们项目中约定好一种适合自己的规范，什么类型的方法以某些形式，约束在某些地方，便于团队内部自己维护和阅读就好啦~
